BikeStore MVC Project/Milestone 3/Controllers/BikesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MileStone2A.Models;

namespace MileStone2A.Controllers
{
    public class BikesController : Controller
    {
        private BikeDBContext db = new BikeDBContext();
        const int DEFAULT_BIKE_CATEGORY_ID = 5;
        // GET: Bikes
        public ActionResult Index()
        {
            var categories = from x in db.ProductCategories
                             where x.ParentProductCategoryID == 1
                             select x;

            ViewBag.Products = db.Products;

            return View(categories.ToList());
        }
        public ActionResult Success()
        {
            return View();
        }


        public ActionResult Mountain()
        {
            var mountain = from x in db.ProductAndDescription
                           where x.Culture == "en" && x.ProductCategoryID == 5
                           select new BikeListModel()
                           {
                               ProductModel = x.ProductModel,
                               Description = x.Description,
                               ProductModelID = x.ProductModelID
                           };
            return View(mountain);
        }

        public ActionResult Road()
        {
            //var road = from x in db.ProductAndDescription where x.Culture == "en" && x.ProductCategoryID == 6 select x;
            var road = from x in db.ProductAndDescription
                       where x.Culture == "en" && x.ProductCategoryID == 6
                       select new BikeListModel()
                       {
                           ProductModel = x.ProductModel,
                           Description = x.Description,
                           ProductModelID = x.ProductModelID
                       };
            return View(road);
        }

        public ActionResult Touring()
        {
            var touring = from x in db.ProductAndDescription
                           where x.Culture == "en" && x.ProductCategoryID == 7
                           select new BikeListModel()
                           {
                               ProductModel = x.ProductModel,
                               Description = x.Description,
                               ProductModelID = x.ProductModelID
                           };
            return View(touring);
        }

        // GET: Bikes/Details/5
        public ActionResult Details(int? id, string searchString)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var ProductDescription = from x in db.Products
                                     where x.ProductModelID == id && x.SellEndDate == null
                                     select x;

            if (!String.IsNullOrEmpty(searchString))
            {
                ProductDescription = from x in db.Products
                                     where x.ProductModelID == id && x.Name.Contains(searchString)
                                     select x;
                //categories = categories.Where(s => s.Name.Contains(searchString));
            }

            

            if (ProductDescription == null)
            {
                return HttpNotFound();
            }
            return View(ProductDescription);
        }
        
        // GET: Bikes/ProductDetails/5
        public ActionResult ProductDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Product product = db.Products.Find(id);

            if (product == null)
            {
                return HttpNotFound();
            }

            return View(product);
        }
    }
}

BikeStore MVC Project/Milestone 3/Controllers/GearController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MileStone2A.Models;
using Milestone_3.Models;

namespace Milestone2B.Controllers
{
    public class GearController : Controller
    {
        private BikeDBContext db = new BikeDBContext();

        // GET: Gear
        public ActionResult Index()
        {
            var categories = from x in db.ProductCategories
                             where x.ProductCategoryID != 1 && x.ParentProductCategoryID == null 
                             select x;
            return View(categories.ToList());
        }
        
        public ActionResult Success()
        {
            return View();
        }

        public ActionResult Components()
        {
            var components = from x in db.ProductCategories
                             where x.ParentProductCategoryID == 2
                             select x;
            return View(components.ToList());
        }

        public ActionResult Clothing()
        {
            var clothing = from x in db.ProductCategories
                             where x.ParentProductCategoryID == 3
                             select x;
            return View(clothing.ToList());
        }

        public ActionResult Accessories()
        {
            var accesories = from x in db.ProductCategories
                           where x.ParentProductCategoryID == 4
                           select x;
            return View(accesories.ToList());
        }

        // GET: Gear/Details/5
        public ActionResult Details(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var gear = from x in db.Products
                       where x.ProductCategoryID == id && x.SellEndDate == null
                       select x;
            if (gear == null)
            {
                return HttpNotFound();
            }
            return View(gear.ToList());
        }
        
        // GET: Bikes/ProductDetails/5
        public ActionResult ProductDetails(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }
    }
}

BikeStore MVC Project/Milestone 3/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MileStone2A.Models;
using Milestone_3.Models;

namespace Milestone_3.Controllers
{
    public class ReviewsController : Controller
    {
        private BikeDBContext db = new BikeDBContext();

        // GET: Reviews
        public ActionResult Index()
        {
            return View(db.Reviews.ToList());
        }



        public ActionResult AddReviews(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            Reviews review = new Reviews();
            review.ProductID = product.ProductID;
            return PartialView(review);
        }
        public ActionResult getReviews(int? id)
        {
            Product product = db.Products.Find(id);
            var productReview = from x in db.Reviews where product.ProductID == x.ProductID select x;
            var reviews = productReview.ToList();
            ViewBag.Count = reviews.Count;

            return PartialView(reviews);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddReviews([Bind(Include = "id,Name,ProductID,Review,Rating")] Reviews reviews)
        {
            if (ModelState.IsValid)
            {
                if (reviews.Name == null || reviews.Name == "" || reviews.Name == " ")
                {
                    reviews.Name = "Anonymous";
                }
                db.Reviews.Add(reviews);
                db.SaveChanges();
                //return RedirectToAction("ReviewSuccess", "Reviews");
            }

            return PartialView(reviews);
        }

        public ActionResult ReviewSuccess()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BikeStore MVC Project/Milestone 3/Views/Reviews/AddReview.cshtml
@model Milestone_3.Models.Reviews

@{
    ViewBag.Title = "AddReview";
}

<h2>Review</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Reviews</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.ProductID, htmlAttributes: new { @class = "control-label col-md-2" })

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @min = "1", @max = "5", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Review, htmlAttributes: new { @class = "control-label col-md-2", @style = "vertical-align:top;" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Review, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

BikeStore MVC Project/Milestone 3/Views/Reviews/AddReviews.cshtml
@model Milestone_3.Models.Reviews

@{
    ViewBag.Title = "AddReview";
}

<h2>Add Review</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.ProductID, htmlAttributes: new { @class = "control-label col-md-2" })

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @min = "1", @max = "5", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Review, htmlAttributes: new { @class = "control-label col-md-2", @style = "vertical-align:top;" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Review, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

BikeStore MVC Project/Milestone 3/Views/Reviews/ReviewSuccess.cshtml
@{
    ViewBag.Title = "ReviewSuccess";
}

<h2>Thank you for the review</h2>


@Html.ActionLink("Back to Bike List", "Index", "Bikes", null, new { @class = "otherlink" })<br />
@Html.ActionLink("Back to Gear List", "Index", "Gear", null, new { @class = "otherlink" })

BikeStore MVC Project/Milestone 3/Views/Reviews/getReviews.cshtml
@model IEnumerable<Milestone_3.Models.Reviews>

@{
    ViewBag.Title = "getReviews";
}

<h2>Reviews</h2>

@if(ViewBag.Count == 0)
{
    <p>No Reviews as of Yet</p>
}
else
{
    <table class="table" align="center">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Review)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Review)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rating)
                </td>
            </tr>
        }

    </table>
}